### ISSUE TITLE
Error: name 'cmd' is not defined

### ISSUE THREAD

**Issue by TheAalCh3m1st** [openai/openai-quickstart-python#20]
I get this error when running the commad...

`python -m venv venv  `  

Output:

`Error: name 'cmd' is not defined`

Python version:

`Python 3.10.9`

**Comment by logankilpatrick** [comment]
Looks like this might be the issue you are having: https://github.com/Datalux/Osintgram/issues/668 please follow up if it does not help.

**Comment by TheAalCh3m1st** [comment]
Will do
