### ISSUE TITLE
Activating venv in Windows

### ISSUE THREAD

**Issue by deniz-tuncbilek** [openai/openai-quickstart-python#30]
Can the readme mention that the file path is venv/Scripts/activate, not venv/bin/activate in Windows?

**Comment by yishairasowsky** [comment]
I agree that this is an issue that should be addressed.

**Comment by yishairasowsky** [comment]
also i think it is 
```
venv/Scripts/activate
```
instead of 
```
. venv/bin/activate
```

**Comment by theo-armour** [comment]
On Win11, using a GIT bash terminal, with Python already installed, this script worked:


$ pip install openai
$ pip install flask
$ pip install dot-env
$ python -m venv venv
$ venv/Scripts/activate
$ pip install -r requirements.txt
$ flask run

**Comment by logankilpatrick** [comment]
Yes, I will update this to be more clear for windows users.
