### ISSUE TITLE
Encountered error while generating package metadata.

### ISSUE THREAD

**Issue by zhijunlu** [openai/openai-quickstart-python#48]
(venv) [root@localhost openai-quickstart-python]# pip3 install -r requirements.txt

         from .macosx_libfile import calculate_macosx_platform_tag
        File "/tmp/pip-build-env-yk9nelsk/overlay/lib/python3.9/site-packages/wheel/macosx_libfile.py", line 43, in <module>
          import ctypes
        File "/usr/local/python3/lib/python3.9/ctypes/__init__.py", line 8, in <module>
          from _ctypes import Union, Structure, Array
      ModuleNotFoundError: No module named '_ctypes'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by logankilpatrick** [comment]
Should be fixed now!
