### ISSUE TITLE
Can't find API key

### ISSUE THREAD

**Issue by ghrasko** [openai/openai-quickstart-python#49]
Not a real coding issue. I am testing on Windows 10. I added the API key to the (renamed) .env file, but it still can't find it. If I add it to the environment by the "set" command in the (elevated) command prompt and then run "flask run", it works fine, but this was clearly not the original intention. Probably I lack some basic information, but can anybody help?

**Comment by ghrasko** [comment]
Hi,

I created a config file called **.env** and added the API key to that:

`OPENAI_API_KEY=<mykey>`

I invoke it the following way:

```
import os
import openai
from dotenv import load_dotenv

def init_gpt():
    load_dotenv()
    openai.api_key = os.getenv("OPENAI_API_KEY")
```

This works for me.

**Comment by kranfnus** [comment]
My problem came from the fact that I was running a too recent version of Python.
One needs to run a Python V3.9.x !

**Comment by ghrasko** [comment]
> My problem came from the fact that I was running a too recent version of Python.
> One needs to run a Python V3.9.x !

Well, I use the most recent Python version with the above code.

**Comment by logankilpatrick** [comment]
We cover this in our getting started guide: https://platform.openai.com/docs/quickstart?context=python
