### ISSUE TITLE
The browser page is different in the flask app than in the python app code.

### ISSUE THREAD

**Issue by maseena** [openai/openai-quickstart-python#53]
When I run Flask and then open up localhost:5000, the displayed page is a simple text-entry box with a "Name my pet" label and a button labeled, "Generate Names", all which work.  However, the app.py code displays an entirely different prompt design.  The app.py prompt starts with "Suggest three names for an animal that is a superhero" and displays examples (e.g., Animal: Cat, Names: Captain SharpClaw,  Agent Fluffball, The Incredible Feline, etc.).  Why is the web page prompt in the flask framework different than the app.py code prompt?

**Comment by logankilpatrick** [comment]
Updated the app! This should be resolved now.
