### ISSUE TITLE
Cannot run python -m venv venv

### ISSUE THREAD

**Issue by kranfnus** [openai/openai-quickstart-python#56]
I installed python v3.10.9 through Anaconda and run a Terminal from Anaconda 

I cloned openai-quickstart-python:

$ git clone https://github.com/openai/openai-quickstart-python.git

After a:

$ cd openai-quickstart-python

I tried to create a new virtual environment:

$ python -m venv venv

Here is the error message:

Error: [WinError 2] The system cannot find the file specified: 'C:\\Users\\...\\openai-quickstart-python\\venv'

What went wrong?

**Comment by Harshitdy** [comment]
Hey! @kranfnus have you tried to create the folder manually 
if not yet then try:

`mkdir venv`

and then try to create the virtual environment using 

`python -m venv venv`

**Comment by kranfnus** [comment]
Tried this and it did not work. 
Finally I used the attrib command line to force access rights...

**Comment by depo101** [comment]
@kranfnus hi, if you install anaconda then 

- you should first create a conda environment 
- then activate it
- then keep going the instruction
