### ISSUE TITLE
[bug] Issue with chatGPT

### ISSUE THREAD

**Issue by Fr-Dae** [openai/openai-quickstart-python#9]
Hello, I found a problem.
I asked chatGPT if it was possible to write a question with a code format

he answered that yes, you have to use the command "code".
like on discord

and adds that you can add a word (like on discord) to force the syntax colorization. 

except that when you actually write in the text field with the ` nothing happens.

nor when sending the message.

moreover it happens very very often that the given answer is cut 
and that the command "continue" does not give the end of the sentence
(in french, is it maybe the problem)

**Comment by logankilpatrick** [comment]
Hey @Fr-Dae! Please add this feedback directly into ChatGPT via the thumbs up / thumbs down button on the web.

**Comment by Fr-Dae** [comment]
ok
